#!/usr/bin/env python3
"""
Patch an extracted Buildroot tree for this installer.

Keeps man/docs when requested and drops small patches into stock
Buildroot package dirs (openvmtools C23, linux-tools PCI) during
``getBuildroot.sh --customize``. Writes ``package/custom-late.mk`` so
br2-external packages under ``buildrootConf/custom_package/`` install
last on a full image build (gcc-standalone-toolchain last among those;
uutils-coreutils is excluded so it can overlay BusyBox applets at
normal order).

Custom packages are not copied into ``package/<name>/``.
``compileBuildroot.sh`` exports ``BR2_EXTERNAL`` so Buildroot sources
the tree via ``external.desc`` / ``Config.in`` / ``external.mk``.
"""

from __future__ import annotations

import argparse
import inspect
import os
import re
import sys
from pathlib import Path


def default_br_path() -> Path:
    """
    Return the extracted Buildroot tree path.

    Uses ``BUILDROOT_BUILDER_DIR`` when that env var is set, otherwise
    ``/builder/Buildroot-Builder``.
    """
    value = os.environ.get("BUILDROOT_BUILDER_DIR") or "/builder/Buildroot-Builder"
    trimmed = value.rstrip("/")
    return Path(trimmed) if trimmed else Path("/builder/Buildroot-Builder")


def default_custom_package_dir() -> Path:
    """
    Return the staged custom-package tree.

    Prefers ``BUILDROOT_CONF_DIR/custom_package``, then a sibling of this
    script (repo / ``/builder/buildrootConf/custom_package``).
    """
    env = os.environ.get("BUILDROOT_CONF_DIR")
    if env:
        return Path(env.rstrip("/")) / "custom_package"
    sibling = Path(__file__).resolve().parent / "buildrootConf" / "custom_package"
    if sibling.is_dir():
        return sibling
    return Path("/builder/buildrootConf/custom_package")


DEFAULT_BR_PATH = default_br_path()

KEEP_MAN_OPTION_BLOCK = inspect.cleandoc("""
    config BR2_KEEP_MAN_PAGES_DOCS
	    bool "Keep manual pages and documentation on target"
	    default n
	    help
	      By default, Buildroot aggressively purges all man, info,
	      and doc directories during target finalization to save
	      space. Enable this option to retain full documentation.
""")

USR_DOC_TOKEN = "$(TARGET_DIR)/usr/doc"
USR_DOC_COMMENT = "#\trm -rf $(TARGET_DIR)/usr/doc\n"
KEEP_DOCS_IFNEQ = "ifneq ($(BR2_KEEP_MAN_PAGES_DOCS),y)\n"
KEEP_DOCS_ENDIF = "endif\n"


def kconfig_package_symbol(package_name: str) -> str:
    """
    Return the ``BR2_PACKAGE_*`` symbol for a package directory name.

    Hyphens become underscores and the rest is uppercased, matching
    Buildroot (``gcc-standalone-toolchain`` →
    ``BR2_PACKAGE_GCC_STANDALONE_TOOLCHAIN``).
    """
    return "BR2_PACKAGE_" + package_name.replace("-", "_").upper()


CUSTOM_LATE_INCLUDE_MARKER = "include package/custom-late.mk"
CUSTOM_LATE_INCLUDE_BLOCK = (
    "\n# Custom packages: on a full image build, delay each custom\n"
    "# package's -install until every other selected package is installed.\n"
    "# Isolated `make <pkg>` is unchanged.\n"
    f"{CUSTOM_LATE_INCLUDE_MARKER}\n"
)
# Install with the rest of $(PACKAGES), not in the late group.
LATE_CUSTOM_SKIP_PACKAGES = frozenset({"uutils-coreutils"})


def iter_custom_packages(custom_dir: Path) -> list[Path]:
    """
    Return staged custom-package directories under *custom_dir*.

    A package is a subdirectory that contains a ``Config.in``. Names are
    sorted so late-mk order stays stable across runs.
    """
    if not custom_dir.is_dir():
        raise SystemExit(f"Error: custom package directory not found: {custom_dir}")
    packages = [
        path
        for path in custom_dir.iterdir()
        if path.is_dir() and (path / "Config.in").is_file()
    ]
    return sorted(packages, key=lambda p: p.name)


def custom_late_mk_text(packages: list[Path]) -> str:
    """
    Return the text of ``package/custom-late.mk`` for *packages*.

    A full image build (empty goals, ``all``, ``target-finalize``,
    ``world``, ``sdk``) adds a Make prerequisite on each enabled
    custom package's ``-install`` stamp so the copy into TARGET_DIR
    waits until every other name in ``$(PACKAGES)`` is installed.
    Packages in ``LATE_CUSTOM_SKIP_PACKAGES`` (uutils-coreutils) are
    omitted so they install in normal dependency order.
    ``gcc-standalone-toolchain-install`` also waits on the other
    late custom packages, so it is last among those. Isolated
    ``make <pkg>`` does not add those edges.
    """
    lines = [
        "# Generated by customizeBuildroot.py. Do not edit.",
        "# Included from the top-level Makefile after package/*/*.mk.",
        "",
        "LATE_CUSTOM_PACKAGES :=",
    ]
    for pkg in packages:
        if pkg.name in LATE_CUSTOM_SKIP_PACKAGES:
            continue
        sym = kconfig_package_symbol(pkg.name)
        lines.append(f"ifeq ($({sym}),y)")
        lines.append(f"LATE_CUSTOM_PACKAGES += {pkg.name}")
        lines.append("endif")
    lines.extend(
        [
            "",
            "LATE_CUSTOM_FULL_BUILD_GOALS := all target-finalize world sdk",
            "LATE_CUSTOM_APPLY :=",
            "ifeq ($(MAKECMDGOALS),)",
            "LATE_CUSTOM_APPLY := y",
            "endif",
            "ifneq ($(filter $(LATE_CUSTOM_FULL_BUILD_GOALS),$(MAKECMDGOALS)),)",
            "LATE_CUSTOM_APPLY := y",
            "endif",
            "",
            "ifeq ($(LATE_CUSTOM_APPLY),y)",
            "ifneq ($(LATE_CUSTOM_PACKAGES),)",
            (
                "$(foreach p,$(LATE_CUSTOM_PACKAGES),"
                "$(eval $(p)-install: "
                "$(filter-out $(LATE_CUSTOM_PACKAGES),$(PACKAGES))))"
            ),
            "ifneq ($(filter gcc-standalone-toolchain,$(LATE_CUSTOM_PACKAGES)),)",
            (
                "gcc-standalone-toolchain-install: "
                "$(filter-out gcc-standalone-toolchain,$(LATE_CUSTOM_PACKAGES))"
            ),
            "endif",
            "endif",
            "endif",
            "",
        ]
    )
    return "\n".join(lines)


def write_custom_late_mk(br_path: Path, packages: list[Path]) -> None:
    """
    Write ``package/custom-late.mk`` and include it from the top Makefile.

    The include is appended once, after all ``package/*/*.mk`` files have
    already been read, so ``$(PACKAGES)`` is complete when the late
    prerequisites are evaluated. br2-external ``external.mk`` is included
    in the same stretch, so custom package names are in ``$(PACKAGES)``.
    """
    dest = br_path / "package" / "custom-late.mk"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(custom_late_mk_text(packages))
    print(f"--> Wrote {dest}")

    makefile = br_path / "Makefile"
    text = makefile.read_text()
    if CUSTOM_LATE_INCLUDE_MARKER not in text:
        makefile.write_text(text.rstrip("\n") + "\n" + CUSTOM_LATE_INCLUDE_BLOCK)
        print(f"--> Appended {CUSTOM_LATE_INCLUDE_MARKER} to {makefile}")
    else:
        print(f"--> {CUSTOM_LATE_INCLUDE_MARKER} already present in {makefile}")


def find_last_endmenu(lines: list[str]) -> int:
    """
    Return the index of the last ``endmenu`` line in *lines*.

    Raises SystemExit if the file has no ``endmenu``.
    """
    last = None
    for i, line in enumerate(lines):
        if line.strip() == "endmenu":
            last = i
    if last is None:
        raise SystemExit("Error: no endmenu found")
    return last


def patch_config_in(path: Path) -> None:
    """
    Insert BR2_KEEP_MAN_PAGES_DOCS in the top-level Config.in.

    Places the keep-docs option immediately before the last ``endmenu``.
    Custom packages are sourced from the br2-external tree, not from
    this file.
    """
    text = path.read_text()
    if "config BR2_KEEP_MAN_PAGES_DOCS" in text:
        print(f"--> BR2_KEEP_MAN_PAGES_DOCS already present in {path}")
        return

    lines = text.splitlines(keepends=True)
    last_endmenu = find_last_endmenu(lines)
    insert = []
    if last_endmenu > 0 and lines[last_endmenu - 1].strip() != "":
        insert.append("\n")
    insert.append(
        KEEP_MAN_OPTION_BLOCK
        if KEEP_MAN_OPTION_BLOCK.endswith("\n")
        else KEEP_MAN_OPTION_BLOCK + "\n"
    )
    insert.append("\n")
    lines[last_endmenu:last_endmenu] = insert
    path.write_text("".join(lines))
    print(f"--> Inserted BR2_KEEP_MAN_PAGES_DOCS before last endmenu in {path}")


def wrap_with_keep_docs_guard(block: str) -> str:
    """
    Wrap a Makefile fragment in ``ifneq ($(BR2_KEEP_MAN_PAGES_DOCS),y)``.

    Used around the target-finalize man/info/doc purge so enabling
    BR2_KEEP_MAN_PAGES_DOCS leaves those trees in the rootfs.
    """
    return f"{KEEP_DOCS_IFNEQ}{block}{KEEP_DOCS_ENDIF}"


def _recipe_body(line: str) -> str:
    """Return a recipe line without leading tabs or a trailing newline."""
    return line.lstrip("\t").rstrip("\n")


def _ends_with_continuation(line: str) -> bool:
    """True when a Makefile line continues onto the next physical line."""
    return line.rstrip("\n").rstrip().endswith("\\")


def find_target_finalize_span(lines: list[str]) -> tuple[int, int]:
    """
    Return [start, end) line indexes covering the target-finalize rule.

    Starts at ``.PHONY: target-finalize`` and runs until the next ``.PHONY:``
    so later Buildroot edits inside the rule still stay in range.
    """
    start = None
    for i, line in enumerate(lines):
        if line.startswith(".PHONY:") and "target-finalize" in line:
            start = i
            break
    if start is None:
        raise SystemExit("Error: .PHONY: target-finalize not found in Makefile")

    end = len(lines)
    for i in range(start + 1, len(lines)):
        if lines[i].startswith(".PHONY:"):
            end = i
            break
    return start, end


def collect_continued_command(lines: list[str], start: int, end: int) -> int:
    """
    Return the exclusive end index of a backslash-continued command.

    *start* is the first physical line of the command. Following lines that
    complete a trailing ``\\`` are included. *end* is the search limit.
    """
    i = start
    while i < end:
        i += 1
        if not _ends_with_continuation(lines[i - 1]):
            break
    return i


def _strip_usr_doc_token(line: str) -> str:
    """Remove ``$(TARGET_DIR)/usr/doc`` as a whole path token from *line*."""
    token = USR_DOC_TOKEN
    body = line.rstrip("\n")
    newline = "\n" if line.endswith("\n") else ""
    continued = body.rstrip().endswith("\\")
    core = body.rstrip()
    if continued:
        core = core[:-1].rstrip()
    prefix_len = len(core) - len(core.lstrip("\t"))
    prefix = core[:prefix_len]
    rest = core[prefix_len:]
    parts = rest.split()
    parts = [p for p in parts if p != token]
    rebuilt = prefix + " ".join(parts)
    if continued:
        rebuilt = rebuilt.rstrip() + " \\"
    return rebuilt + newline


def strip_usr_doc_from_first_rm(lines: list[str], start: int, end: int) -> bool:
    """
    Drop usr/doc from the first ``rm -rf`` under target-finalize.

    That command is the first recipe ``rm -rf`` after ``target-finalize:``,
    including backslash-continued lines. The live token is removed wherever
    it sits; ``USR_DOC_COMMENT`` is inserted immediately below the command.
    """
    rule = None
    for i in range(start, end):
        if lines[i].startswith("target-finalize:"):
            rule = i
            break
    if rule is None:
        raise SystemExit("Error: target-finalize: rule header not found in Makefile")

    rm_start = None
    for i in range(rule + 1, end):
        body = _recipe_body(lines[i]).lstrip()
        if body.startswith("rm -rf"):
            rm_start = i
            break
    if rm_start is None:
        raise SystemExit(
            "Error: first rm -rf in target-finalize not found in Makefile"
        )

    rm_end = collect_continued_command(lines, rm_start, end)
    after = lines[rm_end] if rm_end < len(lines) else ""
    joined = "".join(lines[rm_start:rm_end])
    if USR_DOC_TOKEN not in joined:
        if after == USR_DOC_COMMENT:
            print("--> First target-finalize usr/doc purge already disabled")
            return False
        if after.lstrip("#").lstrip() == "rm -rf $(TARGET_DIR)/usr/doc\n":
            lines[rm_end] = USR_DOC_COMMENT
            print("--> Normalized usr/doc comment to use a tab after #")
            return True
        raise SystemExit(
            "Error: first target-finalize rm -rf does not mention "
            f"{USR_DOC_TOKEN} and has no retention comment"
        )

    new_cmd = [_strip_usr_doc_token(lines[i]) for i in range(rm_start, rm_end)]
    new_cmd = [ln for ln in new_cmd if ln.lstrip("\t").rstrip("\\\n ").strip()]
    if new_cmd and _ends_with_continuation(new_cmd[-1]):
        new_cmd[-1] = new_cmd[-1].rstrip("\n").rstrip().removesuffix("\\").rstrip() + "\n"
    replacement = new_cmd + [USR_DOC_COMMENT]
    lines[rm_start:rm_end] = replacement
    print("--> Removed usr/doc from the first target-finalize rm -rf")
    return True


def wrap_man_purge_block(lines: list[str], start: int, end: int) -> bool:
    """
    Guard the man/info/doc purge with BR2_KEEP_MAN_PAGES_DOCS.

    Locates the recipe ``rm -rf`` that names ``usr/man``, then consumes
    following recipe lines through the ``rmdir`` of ``$(TARGET_DIR)/usr/share``.
    Extra rm lines in that span are kept and wrapped.
    """
    man_start = None
    for i in range(start, end):
        body = _recipe_body(lines[i])
        if "usr/man" in body and "usr/share/man" in body and "rm -rf" in body:
            man_start = i
            break
    if man_start is None:
        raise SystemExit(
            "Error: usr/man purge line not found in target-finalize"
        )

    prev = lines[man_start - 1] if man_start > 0 else ""
    if prev == KEEP_DOCS_IFNEQ:
        print("--> Man/doc purge already wrapped with BR2_KEEP_MAN_PAGES_DOCS")
        return False

    rmdir_idx = None
    gtk_found = False
    for i in range(man_start, end):
        body = _recipe_body(lines[i])
        if "gtk-doc" in body:
            gtk_found = True
        if body.lstrip().startswith("rmdir") and "$(TARGET_DIR)/usr/share" in body:
            rmdir_idx = i
            break
        if i > man_start and not lines[i].startswith("\t"):
            break
    if rmdir_idx is None:
        raise SystemExit(
            "Error: rmdir $(TARGET_DIR)/usr/share not found after usr/man purge"
        )
    if not gtk_found:
        raise SystemExit(
            "Error: gtk-doc purge not found between usr/man and usr/share rmdir"
        )

    block = "".join(lines[man_start : rmdir_idx + 1])
    lines[man_start : rmdir_idx + 1] = [wrap_with_keep_docs_guard(block)]
    print("--> Wrapped man/info/doc purge with BR2_KEEP_MAN_PAGES_DOCS")
    return True


def patch_makefile(path: Path) -> None:
    """
    Stop target-finalize from always deleting man, info, and doc trees.

    Finds the target-finalize rule structurally, strips usr/doc from its first
    ``rm -rf``, and wraps the man/info/doc purge in
    ``ifneq ($(BR2_KEEP_MAN_PAGES_DOCS),y)``.
    """
    lines = path.read_text().splitlines(keepends=True)
    start, end = find_target_finalize_span(lines)
    changed = strip_usr_doc_from_first_rm(lines, start, end)
    start, end = find_target_finalize_span(lines)
    changed = wrap_man_purge_block(lines, start, end) or changed
    if changed:
        path.write_text("".join(lines))


# Kernel 6.14+ moved pcitest from tools/pci to tools/testing/selftests/pci_endpoint
# (kselftest lib.mk requires INSTALL_PATH). The grep-for-install check then
# treats a missing tools/pci/Makefile as "kernel too old".
PCI_BUILD_CMDS_OLD = """define PCI_BUILD_CMDS
	$(Q)if ! grep install $(LINUX_DIR)/tools/pci/Makefile >/dev/null 2>&1 ; then \\
		echo "Your kernel version is too old and does not have install section in the pci tools." ; \\
		echo "At least kernel 4.20 must be used." ; \\
		exit 1 ; \\
	fi

	$(TARGET_MAKE_ENV) $(MAKE) -C $(LINUX_DIR)/tools/pci \\
		$(PCI_MAKE_OPTS)
endef
"""

PCI_BUILD_CMDS_NEW = """define PCI_BUILD_CMDS
	$(Q)if test -f $(LINUX_DIR)/tools/testing/selftests/pci_endpoint/Makefile ; then \\
		PCI_SUBDIR=tools/testing/selftests/pci_endpoint \\
		TEST_GEN_PROGS="TEST_GEN_PROGS=pci_endpoint_test"; \\
	elif test -f $(LINUX_DIR)/tools/pci/Makefile ; then \\
		PCI_SUBDIR=tools/pci; \\
	else \\
		echo "linux-tools pci: no tools/pci or tools/testing/selftests/pci_endpoint Makefile" ; \\
		exit 1 ; \\
	fi ; \\
	$(TARGET_MAKE_ENV) $(MAKE) -C $(LINUX_DIR)/$${PCI_SUBDIR} \\
		$(PCI_MAKE_OPTS) $${TEST_GEN_PROGS}
endef
"""

PCI_INSTALL_CMDS_OLD = """define PCI_INSTALL_TARGET_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) -C $(LINUX_DIR)/tools/pci \\
		$(PCI_MAKE_OPTS) \\
		DESTDIR=$(TARGET_DIR) \\
		install
endef
"""

PCI_INSTALL_CMDS_NEW = """define PCI_INSTALL_TARGET_CMDS
	$(Q)if test -f $(LINUX_DIR)/tools/testing/selftests/pci_endpoint/Makefile ; then \\
		PCI_INSTALL_OPT="INSTALL_PATH=$(TARGET_DIR)/usr/bin" \\
		PCI_SUBDIR=tools/testing/selftests/pci_endpoint \\
		TEST_GEN_PROGS="TEST_GEN_PROGS=pci_endpoint_test"; \\
	else \\
		PCI_INSTALL_OPT="DESTDIR=$(TARGET_DIR)" \\
		PCI_SUBDIR=tools/pci; \\
	fi ; \\
	$(TARGET_MAKE_ENV) $(MAKE) -C $(LINUX_DIR)/$${PCI_SUBDIR} \\
		$(PCI_MAKE_OPTS) $${TEST_GEN_PROGS} \\
		$${PCI_INSTALL_OPT} \\
		install
endef
"""

GREP_INSTALL_RE = re.compile(
    r"if ! grep install (\$\(LINUX_DIR\)/\S+/Makefile) >/dev/null 2>&1"
)


def patch_linux_tool_pci_mk_in(text: str) -> str:
    """
    Point PCI_BUILD_CMDS / PCI_INSTALL_TARGET_CMDS at pci_endpoint when
    tools/pci is gone. Also accept a present tools/pci/Makefile without
    grepping for the word ``install``.
    """
    if "tools/testing/selftests/pci_endpoint" in text:
        return text
    if "define PCI_BUILD_CMDS" not in text:
        return text
    updated = re.sub(
        r"define PCI_BUILD_CMDS\n.*?\nendef\n",
        PCI_BUILD_CMDS_NEW,
        text,
        count=1,
        flags=re.DOTALL,
    )
    updated = re.sub(
        r"define PCI_INSTALL_TARGET_CMDS\n.*?\nendef\n",
        PCI_INSTALL_CMDS_NEW,
        updated,
        count=1,
        flags=re.DOTALL,
    )
    return updated


def patch_linux_tools_grep_install(text: str) -> str:
    """
    Replace ``grep install <Makefile>`` guards with ``test -f <Makefile>``.

    Newer kernel Makefiles often pull ``install`` in from lib.mk, so the
    word is absent from the fragment and the old grep false-fails.
    """
    return GREP_INSTALL_RE.sub(r"if ! test -f \1", text)


def patch_linux_tools(linux_tools_dir: Path) -> None:
    """
    Patch ``package/linux-tools/*.mk.in`` in an extracted Buildroot tree.

    PCI is relocated for kernel 6.14+; remaining tools drop the grep-install
    kernel-too-old check. Missing directory is a no-op (unit tests).
    """
    if not linux_tools_dir.is_dir():
        return
    for path in sorted(linux_tools_dir.glob("*.mk.in")):
        original = path.read_text()
        updated = original
        if path.name == "linux-tool-pci.mk.in":
            updated = patch_linux_tool_pci_mk_in(updated)
        updated = patch_linux_tools_grep_install(updated)
        if updated == original:
            continue
        path.write_text(updated)
        print(f"--> Patched linux-tools fragment {path.name}")


# GCC 15 defaults to C23: empty () is (void). open-vm-tools 11.3.5
# defines MXUserTryAcquireForceFail as Bool (*)() while ulInt.h
# declares Bool (*)(const char *). Upstream PR 751, in 13.0.0.
# Stock package/openvmtools stays in-tree; this file is written into
# that directory at --customize time (not custom_package/).
OPENVMTOOLS_C23_PATCH_STEM = "c23-MXUserTryAcquireForceFail"
OPENVMTOOLS_C23_OLD = "Bool (*MXUserTryAcquireForceFail)() = NULL;"
OPENVMTOOLS_C23_NEW = "Bool (*MXUserTryAcquireForceFail)(const char *) = NULL;"
OPENVMTOOLS_PATCH_INDEX_RE = re.compile(r"^(\d{4})-")
OPENVMTOOLS_C23_PATCH = """\
lib/lock/ul.c: match MXUserTryAcquireForceFail to its prototype

GCC 15 defaults to C23, where an empty parameter list is (void).
The definition in ul.c was Bool (*)(void) while ulInt.h declares
Bool (*)(const char *).

Upstream: https://github.com/vmware/open-vm-tools/pull/751
(incorporated in open-vm-tools 13.0.0)

---
 lib/lock/ul.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/lib/lock/ul.c b/lib/lock/ul.c
--- a/lib/lock/ul.c
+++ b/lib/lock/ul.c
@@ -28,7 +28,7 @@
 static Bool mxInPanic = FALSE;  // track when involved in a panic
 static Bool mxUserCollectLockingTree = FALSE;

-Bool (*MXUserTryAcquireForceFail)() = NULL;
+Bool (*MXUserTryAcquireForceFail)(const char *) = NULL;

 static MX_Rank (*MXUserMxCheckRank)(void) = NULL;
 static void (*MXUserMxLockLister)(void) = NULL;
"""


def openvmtools_c23_patch_present(pkg_dir: Path) -> bool:
    """Return True if a package patch already applies the C23 ul.c fix."""
    if not pkg_dir.is_dir():
        return False
    needle_old = "-" + OPENVMTOOLS_C23_OLD
    needle_new = "+" + OPENVMTOOLS_C23_NEW
    for path in pkg_dir.glob("*.patch"):
        text = path.read_text()
        if needle_old in text and needle_new in text:
            return True
    return False


def next_openvmtools_patch_index(pkg_dir: Path) -> int:
    """Return the next 000N index for a new file in package/openvmtools."""
    highest = 0
    if pkg_dir.is_dir():
        for path in pkg_dir.glob("*.patch"):
            match = OPENVMTOOLS_PATCH_INDEX_RE.match(path.name)
            if match:
                highest = max(highest, int(match.group(1)))
    return highest + 1


def patch_openvmtools(pkg_dir: Path) -> Path | None:
    """
    Write the C23 MXUserTryAcquireForceFail patch into stock openvmtools.

    No-op when the directory is missing (unit tests, incomplete trees) or
    when a patch with the same hunk is already present. Numbering follows
    existing 000N-*.patch files so 2025.08/2026.08 trees (through 0014)
    get 0015-c23-MXUserTryAcquireForceFail.patch.
    """
    if not pkg_dir.is_dir():
        return None
    if openvmtools_c23_patch_present(pkg_dir):
        return None
    dest = pkg_dir / (
        f"{next_openvmtools_patch_index(pkg_dir):04d}-"
        f"{OPENVMTOOLS_C23_PATCH_STEM}.patch"
    )
    dest.write_text(OPENVMTOOLS_C23_PATCH)
    print(f"--> Added openvmtools C23 patch {dest.name}")
    return dest


def customize_buildroot(
    br_path: Path,
    custom_package_dir: Path | None = None,
) -> None:
    """
    Apply stock-tree patches under the extracted Buildroot *br_path*.

    Requires Config.in, package/Config.in, and Makefile at the tree root.
    Inserts BR2_KEEP_MAN_PAGES_DOCS, wraps the man/doc purge, patches
    linux-tools ``*.mk.in`` so PCI follows kernel 6.14+ pci_endpoint,
    and writes the GCC 15 / C23 ul.c fix into stock
    ``package/openvmtools/``. Scans *custom_package_dir* and writes
    ``package/custom-late.mk`` so those packages install last on a
    full image build (uutils-coreutils skipped; gcc-standalone last
    among the rest). Does not copy package files into ``package/``.
    """
    config_in = br_path / "Config.in"
    makefile = br_path / "Makefile"
    custom_dir = custom_package_dir or default_custom_package_dir()

    if not config_in.is_file():
        raise SystemExit(
            f"Error: Buildroot is not extracted at {br_path} (missing Config.in)."
        )
    if not makefile.is_file():
        raise SystemExit(
            f"Error: Buildroot is not extracted at {br_path} (missing Makefile)."
        )
    pkg_config_in = br_path / "package" / "Config.in"
    if not pkg_config_in.is_file():
        raise SystemExit(
            f"Error: Buildroot is not extracted at {br_path} (missing package/Config.in)."
        )

    packages = iter_custom_packages(custom_dir)
    write_custom_late_mk(br_path, packages)
    patch_config_in(config_in)
    patch_makefile(makefile)
    patch_linux_tools(br_path / "package" / "linux-tools")
    patch_openvmtools(br_path / "package" / "openvmtools")
    print("--> customizeBuildroot.py completed successfully.")


def main(argv: list[str] | None = None) -> int:
    """
    Parse CLI arguments and run customize_buildroot().

    Parameters
    ----------
    argv:
        Argument list without the program name. ``None`` uses ``sys.argv[1:]``.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Patch extracted Buildroot sources for man/docs retention, "
            "stock-package compile fixes, and late custom-package install."
        )
    )
    parser.add_argument(
        "--br-path",
        type=Path,
        default=DEFAULT_BR_PATH,
        help=f"Buildroot source root (default: {DEFAULT_BR_PATH})",
    )
    parser.add_argument(
        "--custom-package-dir",
        type=Path,
        default=None,
        help=(
            "br2-external custom_package tree used to generate "
            "package/custom-late.mk (default: BUILDROOT_CONF_DIR/custom_package)"
        ),
    )
    args = parser.parse_args(argv)
    customize_buildroot(args.br_path, args.custom_package_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
