"""Write package/custom-late.mk so br2-external packages install last."""

from __future__ import annotations

from pathlib import Path

from ..util import kconfig_package_symbol

CUSTOM_LATE_INCLUDE_MARKER = "include package/custom-late.mk"
CUSTOM_LATE_INCLUDE_BLOCK = (
    "\n# Custom packages: on a full image build, delay each custom\n"
    "# package's -install until every other selected package is installed.\n"
    "# Isolated `make <pkg>` is unchanged.\n"
    f"{CUSTOM_LATE_INCLUDE_MARKER}\n"
)
# Install with the rest of $(PACKAGES), not in the late group.
LATE_CUSTOM_SKIP_PACKAGES = frozenset({"uutils-coreutils"})
# Library-like custom packages that other custom packages depend on.
# They go in LATE_CUSTOM_PACKAGES_LIBS and install before every package
# in LATE_CUSTOM_PACKAGES (after all non-custom packages). Such a
# package must not depend on any package in LATE_CUSTOM_PACKAGES.
LATE_CUSTOM_LIB_PACKAGES = frozenset({"gcc-standalone-toolchain"})


def iter_custom_packages(custom_dir: Path) -> list[Path]:
    """
    Return staged custom-package directories under *custom_dir*.

    A package is a subdirectory that contains a ``Config.in``. Names are
    sorted so late-mk order stays stable across runs.
    """
    if not custom_dir.is_dir():
        raise SystemExit(f"Error: custom package directory not found: {custom_dir}")
    packages = [
        path
        for path in custom_dir.iterdir()
        if path.is_dir() and (path / "Config.in").is_file()
    ]
    return sorted(packages, key=lambda p: p.name)


def custom_late_mk_text(packages: list[Path]) -> str:
    """
    Return the text of ``package/custom-late.mk`` for *packages*.

    A full image build (empty goals, ``all``, ``target-finalize``,
    ``world``, ``sdk``) adds a Make prerequisite on each enabled
    custom package's ``-install`` stamp so the copy into TARGET_DIR
    waits until every other name in ``$(PACKAGES)`` is installed.
    Packages in ``LATE_CUSTOM_SKIP_PACKAGES`` (uutils-coreutils) are
    omitted so they install in normal dependency order.
    Packages in ``LATE_CUSTOM_LIB_PACKAGES`` (gcc-standalone-toolchain)
    go in ``LATE_CUSTOM_PACKAGES_LIBS`` instead: they install first
    among the custom packages, and every package in
    ``LATE_CUSTOM_PACKAGES`` waits for them. That lets a late package
    (dotnet10, pwsh7) list a lib package in its ``_DEPENDENCIES``
    without a cycle. Isolated ``make <pkg>`` does not add those edges.
    """
    lines = [
        "# Generated by customizeBuildroot. Do not edit.",
        "# Included from the top-level Makefile after package/*/*.mk.",
        "",
        "LATE_CUSTOM_PACKAGES_LIBS :=",
        "LATE_CUSTOM_PACKAGES :=",
    ]
    for pkg in packages:
        if pkg.name in LATE_CUSTOM_SKIP_PACKAGES:
            continue
        sym = kconfig_package_symbol(pkg.name)
        lines.append(f"ifeq ($({sym}),y)")
        group = (
            "LATE_CUSTOM_PACKAGES_LIBS"
            if pkg.name in LATE_CUSTOM_LIB_PACKAGES
            else "LATE_CUSTOM_PACKAGES"
        )
        lines.append(f"{group} += {pkg.name}")
        lines.append("endif")
    lines.extend(
        [
            "",
            "LATE_CUSTOM_FULL_BUILD_GOALS := all target-finalize world sdk",
            "LATE_CUSTOM_APPLY :=",
            "ifeq ($(MAKECMDGOALS),)",
            "LATE_CUSTOM_APPLY := y",
            "endif",
            "ifneq ($(filter $(LATE_CUSTOM_FULL_BUILD_GOALS),$(MAKECMDGOALS)),)",
            "LATE_CUSTOM_APPLY := y",
            "endif",
            "",
            "ifeq ($(LATE_CUSTOM_APPLY),y)",
            "LATE_CUSTOM_ALL := $(LATE_CUSTOM_PACKAGES_LIBS) $(LATE_CUSTOM_PACKAGES)",
            "ifneq ($(strip $(LATE_CUSTOM_ALL)),)",
            "# Every custom package waits for all non-custom packages.",
            (
                "$(foreach p,$(LATE_CUSTOM_ALL),"
                "$(eval $(p)-install: "
                "$(filter-out $(LATE_CUSTOM_ALL),$(PACKAGES))))"
            ),
            "# Lib packages install first among the custom ones.",
            "ifneq ($(strip $(LATE_CUSTOM_PACKAGES_LIBS)),)",
            (
                "$(foreach p,$(LATE_CUSTOM_PACKAGES),"
                "$(eval $(p)-install: $(LATE_CUSTOM_PACKAGES_LIBS)))"
            ),
            "endif",
            "endif",
            "endif",
            "",
        ]
    )
    return "\n".join(lines)


def write_custom_late_mk(br_path: Path, packages: list[Path]) -> None:
    """
    Write ``package/custom-late.mk`` and include it from the top Makefile.

    The include is appended once, after all ``package/*/*.mk`` files have
    already been read, so ``$(PACKAGES)`` is complete when the late
    prerequisites are evaluated. br2-external ``external.mk`` is included
    in the same stretch, so custom package names are in ``$(PACKAGES)``.
    """
    dest = br_path / "package" / "custom-late.mk"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(custom_late_mk_text(packages))
    print(f"--> Wrote {dest}")

    makefile = br_path / "Makefile"
    text = makefile.read_text()
    if CUSTOM_LATE_INCLUDE_MARKER not in text:
        makefile.write_text(text.rstrip("\n") + "\n" + CUSTOM_LATE_INCLUDE_BLOCK)
        print(f"--> Appended {CUSTOM_LATE_INCLUDE_MARKER} to {makefile}")
    else:
        print(f"--> {CUSTOM_LATE_INCLUDE_MARKER} already present in {makefile}")
